version: '3'
services:
  server:
    build: ./server
    environment:
      - DOT_ENV=.env.production.local
    ports:
      - "4000:4000"
  client:
    build: ./client
    environment:
      - DOT_ENV=.env.production.local
    ports:
      - "5000:5000"